### ISSUE TITLE
SVG Images in the HTML Broken After Critical

### ISSUE THREAD

**Issue by superKalo** [addyosmani/critical#63]
Hello all,

I am having an interesting issue in my latest project. When I trigger Critical to inject the critical styles in my html (dest: '_site/index.html') it breaks my SVG logo image.
Here is the image before:

``` html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 563 87.9" enable-background="new 0 0 563 87.9" xml:space="preserve" width="167px" height="26px" fill="#fff">
    <g>
        <g>
            <path d="M137.6,23.6h-15.7v-3.1h34.8v3.1H141v42h-3.3V23.6z"/>
            <path d="M173.3,20.5h18.9c5.5,0,10,1.7,12.7,4.4c2.1,2.1,3.4,5.1,3.4,8.4v0.1c0,7.5-5.6,11.8-13.2,12.9L210,65.6h-4.2l-14.4-18.7h-0.1h-14.6v18.7h-3.3V20.5z M191.8,43.9c7.5,0,13.1-3.8,13.1-10.3v-0.1c0-6-4.8-9.8-12.9-9.8h-15.4v20.3H191.8z"/>
            <path d="M225.6,46.9V20.5h3.3v26c0,10.6,5.7,16.7,15.3,16.7c9.1,0,15-5.5,15-16.4V20.5h3.3v25.9c0,12.9-7.5,19.8-18.5,19.8C233.2,66.3,225.6,59.5,225.6,46.9z"/>
            <path d="M281.6,20.5h32.1v3.1H285v17.7h25.8v3.1H285v18.1h29v3.1h-32.4V20.5z"/>
            <path d="M326.1,20.5H337l11.8,31.7l11.8-31.7h10.7L353,65.9h-8.8L326.1,20.5z"/>
            <path d="M393.6,20.2h9.1l19.3,45.4h-10.4l-4.1-10.1h-19.1l-4.1,10.1h-10.1L393.6,20.2z M404.1,46.7l-6-14.6l-6,14.6H404.1z"/>
            <path d="M433.2,46.3V20.5h9.9V46c0,7.3,3.7,11.1,9.7,11.1c6.1,0,9.7-3.7,9.7-10.8V20.5h9.9V46c0,13.6-7.7,20.3-19.8,20.3C440.6,66.3,433.2,59.5,433.2,46.3z"/>
            <path d="M489,20.5h9.9v36h22.5v9H489V20.5z"/>
            <path d="M539.3,29.7h-13.7v-9.1H563v9.1h-13.7v35.9h-9.9V29.7z"/>
        </g>
        <g>
            <path d="M63.9,17.6H35.5L22.8,36.5l26.8,26.5l26.8-26.6L63.9,17.6z M60.1,41.1l-0.5,1l-0.4,0.6l-0.7-0.4l-6.7-3.7c-0.6,0.6-1.4,0.9-2.3,0.9c-0.9,0-1.7-0.3-2.3-0.9l-6.7,3.7L40,42.7l-0.4-0.6l-0.5-1l-0.4-0.7l0.7-0.4l6.9-3.8c0,0,0,0,0,0c0-1.3,0.8-2.5,2-3v-7v-0.7H49h1.1h0.7v0.7v7c1.2,0.5,2.1,1.7,2.1,3.1c0,0,0,0,0,0l6.9,3.8l0.7,0.4L60.1,41.1z"/>
            <path d="M73.3,0H26.1L0,38.8l49.6,49.1L99,38.8L73.3,0zM49.6,67.8L18.5,37l15.3-22.7h31.9l15,22.6L49.6,67.8z"/>
        </g>
    </g>
</svg>
```

And here is the image after:

``` html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewbox="0 0 563 87.9" enable-background="new 0 0 563 87.9" xml:space="preserve" width="167px" height="26px" fill="#fff">
    <g>
        <g>
            <path d="M137.6,23.6h-15.7v-3.1h34.8v3.1H141v42h-3.3V23.6z">
            <path d="M173.3,20.5h18.9c5.5,0,10,1.7,12.7,4.4c2.1,2.1,3.4,5.1,3.4,8.4v0.1c0,7.5-5.6,11.8-13.2,12.9L210,65.6h-4.2l-14.4-18.7h-0.1h-14.6v18.7h-3.3V20.5z M191.8,43.9c7.5,0,13.1-3.8,13.1-10.3v-0.1c0-6-4.8-9.8-12.9-9.8h-15.4v20.3H191.8z">
            <path d="M225.6,46.9V20.5h3.3v26c0,10.6,5.7,16.7,15.3,16.7c9.1,0,15-5.5,15-16.4V20.5h3.3v25.9c0,12.9-7.5,19.8-18.5,19.8C233.2,66.3,225.6,59.5,225.6,46.9z">
            <path d="M281.6,20.5h32.1v3.1H285v17.7h25.8v3.1H285v18.1h29v3.1h-32.4V20.5z">
            <path d="M326.1,20.5H337l11.8,31.7l11.8-31.7h10.7L353,65.9h-8.8L326.1,20.5z">
            <path d="M393.6,20.2h9.1l19.3,45.4h-10.4l-4.1-10.1h-19.1l-4.1,10.1h-10.1L393.6,20.2z M404.1,46.7l-6-14.6l-6,14.6H404.1z">
            <path d="M433.2,46.3V20.5h9.9V46c0,7.3,3.7,11.1,9.7,11.1c6.1,0,9.7-3.7,9.7-10.8V20.5h9.9V46c0,13.6-7.7,20.3-19.8,20.3C440.6,66.3,433.2,59.5,433.2,46.3z">
            <path d="M489,20.5h9.9v36h22.5v9H489V20.5z">
            <path d="M539.3,29.7h-13.7v-9.1H563v9.1h-13.7v35.9h-9.9V29.7z">
        </g>
        <g>
            <path d="M63.9,17.6H35.5L22.8,36.5l26.8,26.5l26.8-26.6L63.9,17.6z M60.1,41.1l-0.5,1l-0.4,0.6l-0.7-0.4l-6.7-3.7c-0.6,0.6-1.4,0.9-2.3,0.9c-0.9,0-1.7-0.3-2.3-0.9l-6.7,3.7L40,42.7l-0.4-0.6l-0.5-1l-0.4-0.7l0.7-0.4l6.9-3.8c0,0,0,0,0,0c0-1.3,0.8-2.5,2-3v-7v-0.7H49h1.1h0.7v0.7v7c1.2,0.5,2.1,1.7,2.1,3.1c0,0,0,0,0,0l6.9,3.8l0.7,0.4L60.1,41.1z">
            <path d="M73.3,0H26.1L0,38.8l49.6,49.1L99,38.8L73.3,0zM49.6,67.8L18.5,37l15.3-22.7h31.9l15,22.6L49.6,67.8z">
        </g>
    </g>
</svg>
```

Notice how by the end of each **path** element in the input we have a self closing tag "/>". However in the output the self closing tag is transformed to just ">", without the "/" and unfortunately the SVG is messed up :(

Can somebody help me?

Thanks in advance,
Kalo.

**Comment by bezoerb** [comment]
This looks like an issue with cheerio.
See https://github.com/cheeriojs/cheerio/issues/521
I'll check if there is a workaround for this

**Comment by bezoerb** [comment]
@superKalo the SVG issue should be fixed in `master`. Wanna give it another try?

**Comment by superKalo** [comment]
@bezoerb thanks!
I am actually using it via [the grunt plugin](https://github.com/bezoerb/grunt-critical), so I guess the grunt plugin needs to be updated too.

**Comment by peterblazejewicz** [comment]
@bezoerb 
> the SVG issue should be fixed in master. Wanna give it another try?
Yes, that's correct. If we prepare `grunt-critical` install with master our problem is fixed!
Thanks!

**Comment by addyosmani** [comment]
Looks like this should be good to go once we've bumped `grunt-critical`. Local updating and linking seems to suggest this will address things for @superKalo. Thanks for being on top of this @bezoerb!

**Comment by samccone** [comment]
:+1: @peterblazejewicz great find, good catch, thanks @addyosmani and @bezoerb as always

**Comment by bezoerb** [comment]
@addyosmani we need to bump `critical` first to bump the dependency in `grunt-critical`

**Comment by addyosmani** [comment]
@bezoerb I think it's time for another release. Lets do this shortly. Sorry for being afk this past week! Catching up with threads now.

**Comment by samccone** [comment]
Let me know if I can be of any help here

**Comment by samccone** [comment]
looks like this haas been fixed in the latest release, thanks guys @bezoerb @addyosmani

**Comment by bezoerb** [comment]
@samccone yepp, `critical` and `grunt-critical` are both patched. :)

**Comment by diagramatics** [comment]
Hm, this hasn't worked properly on my end. Tried even using `master` and the output still breaks my inline SVG. I'm using io.js and Windows 8.1.

**Comment by bezoerb** [comment]
@diagramatics which part of the svg is broken? 
It seems that there's still an issue in `cheeriojs`. See https://github.com/cheeriojs/cheerio/issues/521

**Comment by diagramatics** [comment]
The same as above, `<path />` tags lost the slash. Converting them to normal tags (`<path></path>`) doesn't work too.

**Comment by diagramatics** [comment]
So I manually bumped cheerio to 0.19.0 and everything works fine now. Thanks for the issue reference!

**Comment by bezoerb** [comment]
just bumped [`inline-critical`](https://github.com/bezoerb/inline-critical/blob/master/package.json#L24)

**Comment by addyosmani** [comment]
Do we need to bump inline-critical version used here too?

**Comment by bezoerb** [comment]
I thought patch versions would be loaded automatically but it seemed that this wasn't the case for the cheerio patch so i've just bumped & fixed the versions over there.
I'll try later today and give you a hint.

**Comment by bezoerb** [comment]
@addyosmani looks good. No need for a version bumb.

**Comment by addyosmani** [comment]
:+1:

**Comment by catalinred** [comment]
Hi,

Not sure if it's ok to resurrect this, but I think this issue "is happening" again. 

I had to remove `critical` this morning from within a project at work because the inline SVG's got broken after the `critical` task ran.

As far as I tested, is the same behavior as @superKalo described above.

My setup includes critical w/ [Gulp](https://www.npmjs.com/package/critical#gulp)

Looking forward to hearing from you.
Thanks!

**Comment by bezoerb** [comment]
I will check this weekend

**Comment by bezoerb** [comment]
Currently this looks like another issue in `inline-critical` or `cheerio`.
In my tests everything works fine if i remove the `<title>Title</title>` tag.
As soon as there's a `<title>` inside the svg things get messy.

I'll investigate further to see if this can be fixed in inline-critical or if we have to file a bug over at cheerio/htmlparser2

**Comment by bezoerb** [comment]
Opened a PR over at htmlparser2: https://github.com/fb55/htmlparser2/pull/259

**Comment by bezoerb** [comment]
I also pushed a temporary fix to inline-critical so SVGs should be fine from now on.

@catalinred: Would you mind checking again with `critical@next`?

**Comment by catalinred** [comment]
@bezoerb Sorry for the delay, I had some days off.

Just tested this morning with critical@next (2.0.0-4) and apparently it doesn't work for me at all, it doesn't insert the inline style in my .html files anymore. 

In case it helps, I'm on a Windows 10 machine with Node v10.14.1 and I'm getting the following whenever using critical > 2.0:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

> [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know, maybe it's just me?! I will try to run things on a Linux machine later today...

**Comment by bezoerb** [comment]
@catalinred: can you provide a test case for this or share the files/config to reproduce the issue? This would massively speed up the fix :)

**Comment by catalinred** [comment]
> @catalinred: can you provide a test case for this or share the files/config to reproduce the issue? This would massively speed up the fix :)

@bezoerb  I'm sorry for replying that late. The truth is I'm not able to replicate my project's issue in a minimal scenario.  Will have to dig deeper to see what I'm missing out in there.

**Comment by bezoerb** [comment]
@catalinred: i've updated [`inline-critical`](https://github.com/bezoerb/inline-critical) which is used internally to inline the critical css.

It now uses `jsdom` instead of `cheerio` for DOM manipulation and the parsing is limited to the document head.
The document body should remain unchanged besides the `<noscript>` blocks which are added to the end of the document.

So maybe a fresh installation of `critical@next` (v2.0.0-10) could resolve your problem

**Comment by catalinred** [comment]
> @catalinred: i've updated [`inline-critical`](https://github.com/bezoerb/inline-critical) which is used internally to inline the critical css.
> 
> It now uses `jsdom` instead of `cheerio` for DOM manipulation and the parsing is limited to the document head.
> The document body should remain unchanged besides the `<noscript>` blocks which are added to the end of the document.
> 
> So maybe a fresh installation of `critical@next` (v2.0.0-10) could resolve your problem

Hi @bezoerb, here's what happens now with the `2.0.0-10` critical version: 

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7AABD121A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF7AABAA5B6 node::MakeCallback+4518
 3: 00007FF7AABAAFA0 node_module_register+2160
 4: 00007FF7AAE3B3EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7AAE3B31F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7AB379304 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF7AB36FA67 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF7AB36DFDC v8::internal::ScavengeJob::operator=+18748
 9: 00007FF7AB376F57 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF7AB376FD6 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF7AAF19DD7 v8::internal::Factory::NewFillerObject+55
12: 00007FF7AAFB1F7D v8::internal::WasmJs::Install+30749
13: 0000002FF06DC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134`

- Windows machine
- Node.js v10.15.0
- critical 2.0.0-10

I didn't give up yet, but I'm so close. Still working on a minimal scenario to replicate this behavior.

Thanks again for your hard work. :)

**Comment by bezoerb** [comment]
@catalinred: i think i managed to get rid of the memory error :)
Would you mind trying again? (Critical should be in version v2.0.0-12)
